# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Healthy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Healthy
  pod 'AlamofireObjectMapper'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'AlamofireSwiftyJSON'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'Kingfisher', '~> 4.0'
  pod 'CryptoSwift'
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'RealmSwift'

  pod "MBCircularProgressBar"

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'

  pod 'FBSDKLoginKit'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'

  pod 'GoogleSignIn'

end
