# Uncomment the next line to define a global platform for your project
# platform :ios, '9.2'

target 'Fitness_App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fitness_App

  #swiftjson
  pod 'SwiftyJSON', '~> 4.0'
  pod 'AlamofireSwiftyJSON'
  pod 'MBProgressHUD', '~> 1.1.0'
  
  pod 'Kingfisher', '~> 4.0'
  pod 'CryptoSwift'
  pod 'FBSDKLoginKit'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'GoogleSignIn'
  pod 'Charts'
  pod 'RealmSwift'

  pod "MBCircularProgressBar"

end
