# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fitness_App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fitness_App

  #swiftjson
  pod 'SwiftyJSON', '~> 4.0'
  pod 'AlamofireSwiftyJSON'
  pod 'Kingfisher', '~> 4.0'
  pod 'CryptoSwift'
  pod 'MBProgressHUD', '~> 1.1.0'

end
